name: Updated Framework on Website

on: push

jobs:
  update-aws:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Master
        uses: actions/checkout@master
      
      - name: Upload S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: './'
          DEST_DIR: 'js/works/ucl_cg_framework'
